'use client';
import { useState } from 'react';
import Link from 'next/link';
import Navbar from '../components/Navbar';

export default function HtaccessGenerator() {
  const [options, setOptions] = useState({
    forceHttps: true,
    forceWww: false,
    removeWww: false,
    enableGzip: true,
    browserCache: true,
    preventHotlinking: false,
    blockBadBots: true,
    customRedirects: '',
    denyIPs: '',
    enableCors: false,
    customErrorPages: true,
    preventDirectoryBrowsing: true,
    hotlinkDomain: '',
  });
  const [copied, setCopied] = useState(false);
  const [activeSection, setActiveSection] = useState('performance');

  const toggle = (key: string) => setOptions(prev => ({ ...prev, [key]: !prev[key as keyof typeof prev] }));

  const generateHtaccess = () => {
    const lines: string[] = ['# Generated by DevLpers .htaccess Generator', '# https://develpers.com/htaccess-generator', ''];

    if (options.preventDirectoryBrowsing) {
      lines.push('# Prevent Directory Browsing');
      lines.push('Options -Indexes');
      lines.push('');
    }

    if (options.forceHttps) {
      lines.push('# Force HTTPS');
      lines.push('RewriteEngine On');
      lines.push('RewriteCond %{HTTPS} off');
      lines.push('RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]');
      lines.push('');
    }

    if (options.forceWww && !options.removeWww) {
      lines.push('# Force WWW');
      lines.push('RewriteEngine On');
      lines.push('RewriteCond %{HTTP_HOST} !^www\\. [NC]');
      lines.push('RewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [R=301,L]');
      lines.push('');
    }

    if (options.removeWww && !options.forceWww) {
      lines.push('# Remove WWW');
      lines.push('RewriteEngine On');
      lines.push('RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]');
      lines.push('RewriteRule ^ https://%1%{REQUEST_URI} [R=301,L]');
      lines.push('');
    }

    if (options.enableGzip) {
      lines.push('# Enable Gzip Compression');
      lines.push('<IfModule mod_deflate.c>');
      lines.push('  AddOutputFilterByType DEFLATE text/html text/plain text/xml');
      lines.push('  AddOutputFilterByType DEFLATE text/css text/javascript');
      lines.push('  AddOutputFilterByType DEFLATE application/javascript application/json');
      lines.push('  AddOutputFilterByType DEFLATE image/svg+xml');
      lines.push('</IfModule>');
      lines.push('');
    }

    if (options.browserCache) {
      lines.push('# Browser Caching');
      lines.push('<IfModule mod_expires.c>');
      lines.push('  ExpiresActive On');
      lines.push('  ExpiresByType image/jpg "access plus 1 year"');
      lines.push('  ExpiresByType image/jpeg "access plus 1 year"');
      lines.push('  ExpiresByType image/png "access plus 1 year"');
      lines.push('  ExpiresByType image/webp "access plus 1 year"');
      lines.push('  ExpiresByType image/gif "access plus 1 year"');
      lines.push('  ExpiresByType text/css "access plus 1 month"');
      lines.push('  ExpiresByType application/javascript "access plus 1 month"');
      lines.push('  ExpiresByType text/html "access plus 1 week"');
      lines.push('</IfModule>');
      lines.push('');
    }

    if (options.enableCors) {
      lines.push('# Enable CORS');
      lines.push('<IfModule mod_headers.c>');
      lines.push('  Header set Access-Control-Allow-Origin "*"');
      lines.push('  Header set Access-Control-Allow-Methods "GET, POST, OPTIONS"');
      lines.push('  Header set Access-Control-Allow-Headers "Content-Type"');
      lines.push('</IfModule>');
      lines.push('');
    }

    if (options.blockBadBots) {
      lines.push('# Block Bad Bots');
      lines.push('SetEnvIfNoCase User-Agent "AhrefsBot" bad_bot');
      lines.push('SetEnvIfNoCase User-Agent "SemrushBot" bad_bot');
      lines.push('SetEnvIfNoCase User-Agent "MJ12bot" bad_bot');
      lines.push('SetEnvIfNoCase User-Agent "DotBot" bad_bot');
      lines.push('SetEnvIfNoCase User-Agent "BLEXBot" bad_bot');
      lines.push('<Limit GET POST HEAD>');
      lines.push('  Order Allow,Deny');
      lines.push('  Allow from all');
      lines.push('  Deny from env=bad_bot');
      lines.push('</Limit>');
      lines.push('');
    }

    if (options.preventHotlinking && options.hotlinkDomain) {
      lines.push('# Prevent Hotlinking');
      lines.push('RewriteEngine On');
      lines.push(`RewriteCond %{HTTP_REFERER} !^$`);
      lines.push(`RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?${options.hotlinkDomain.replace(/\./g, '\\.')} [NC]`);
      lines.push('RewriteRule \\.(jpg|jpeg|png|gif|webp)$ - [F]');
      lines.push('');
    }

    if (options.denyIPs.trim()) {
      lines.push('# Block IP Addresses');
      options.denyIPs.split('\n').forEach(ip => {
        if (ip.trim()) lines.push(`Deny from ${ip.trim()}`);
      });
      lines.push('');
    }

    if (options.customErrorPages) {
      lines.push('# Custom Error Pages');
      lines.push('ErrorDocument 404 /404.html');
      lines.push('ErrorDocument 403 /403.html');
      lines.push('ErrorDocument 500 /500.html');
      lines.push('');
    }

    if (options.customRedirects.trim()) {
      lines.push('# Custom Redirects');
      options.customRedirects.split('\n').forEach(redirect => {
        const parts = redirect.trim().split(' ');
        if (parts.length >= 2) lines.push(`Redirect 301 ${parts[0]} ${parts[1]}`);
      });
      lines.push('');
    }

    return lines.join('\n');
  };

  const output = generateHtaccess();

  const copyCode = () => {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadFile = () => {
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = '.htaccess';
    a.click();
  };

  const ToggleOption = ({ label, desc, optionKey }: { label: string; desc: string; optionKey: string }) => (
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0.85rem 0', borderBottom: '1px solid #f0f0f0' }}>
      <div>
        <div style={{ fontWeight: 500, fontSize: '0.88rem', color: '#404145' }}>{label}</div>
        <div style={{ color: '#95979d', fontSize: '0.75rem' }}>{desc}</div>
      </div>
      <button onClick={() => toggle(optionKey)} style={{
        width: '44px', height: '24px', borderRadius: '12px', border: 'none', cursor: 'pointer',
        background: options[optionKey as keyof typeof options] ? '#1dbf73' : '#e4e5e7',
        position: 'relative', transition: 'background 0.2s', flexShrink: 0,
      }}>
        <span style={{
          position: 'absolute', top: '2px',
          left: options[optionKey as keyof typeof options] ? '22px' : '2px',
          width: '20px', height: '20px', borderRadius: '50%', background: '#fff',
          transition: 'left 0.2s', display: 'block',
        }} />
      </button>
    </div>
  );

  return (
    <div style={{ minHeight: '100vh', background: '#f8fafc' }}>
      <Navbar />
      <div style={{ paddingTop: '64px' }}>

        {/* HERO */}
        <div style={{ background: 'linear-gradient(135deg, #1a1a2e 0%, #0f3460 100%)', padding: '3.5rem 5%', textAlign: 'center' }}>
          <div style={{ maxWidth: '750px', margin: '0 auto' }}>
            <div style={{ display: 'inline-block', background: 'rgba(29,191,115,0.15)', border: '1px solid rgba(29,191,115,0.3)', borderRadius: '100px', padding: '5px 18px', fontSize: '0.82rem', color: '#1dbf73', fontWeight: 700, marginBottom: '1.25rem' }}>
              ⚙️ Free Developer Tool
            </div>
            <h1 style={{ fontFamily: 'Inter', fontWeight: 800, fontSize: 'clamp(1.8rem, 4vw, 2.75rem)', color: '#fff', marginBottom: '0.75rem', lineHeight: 1.2 }}>
              .htaccess Generator<br />
              <span style={{ color: '#1dbf73' }}>Apache Configuration Made Easy</span>
            </h1>
            <p style={{ color: 'rgba(255,255,255,0.75)', fontSize: '0.95rem', lineHeight: 1.7 }}>
              Generate .htaccess files with HTTPS redirect, Gzip compression, browser caching, bot blocking and more. Free, download ready.
            </p>
          </div>
        </div>

        <div style={{ padding: '2.5rem 5%', maxWidth: '1100px', margin: '0 auto' }}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem', marginBottom: '2rem' }}>

            {/* LEFT */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>

              {/* Section Tabs */}
              <div style={{ display: 'flex', gap: '0', border: '1px solid #e4e5e7', borderRadius: '8px', overflow: 'hidden', background: '#fff' }}>
                {[
                  { id: 'performance', label: '⚡ Performance' },
                  { id: 'security', label: '🔒 Security' },
                  { id: 'advanced', label: '⚙️ Advanced' },
                ].map(t => (
                  <button key={t.id} onClick={() => setActiveSection(t.id)} style={{
                    flex: 1, padding: '10px 6px', border: 'none', fontSize: '0.78rem',
                    background: activeSection === t.id ? '#1a1a2e' : '#fff',
                    color: activeSection === t.id ? '#fff' : '#62646a',
                    fontWeight: activeSection === t.id ? 700 : 400, cursor: 'pointer',
                  }}>{t.label}</button>
                ))}
              </div>

              <div style={{ background: '#fff', border: '1px solid #e4e5e7', borderRadius: '12px', padding: '1.5rem' }}>
                {activeSection === 'performance' && (
                  <>
                    <ToggleOption label="Force HTTPS" desc="Redirect all HTTP to HTTPS (301)" optionKey="forceHttps" />
                    <ToggleOption label="Enable Gzip Compression" desc="Compress HTML, CSS, JS for faster loading" optionKey="enableGzip" />
                    <ToggleOption label="Browser Caching" desc="Cache images 1 year, CSS/JS 1 month" optionKey="browserCache" />
                    <ToggleOption label="Force WWW" desc="Redirect non-www to www" optionKey="forceWww" />
                    <ToggleOption label="Remove WWW" desc="Redirect www to non-www" optionKey="removeWww" />
                  </>
                )}

                {activeSection === 'security' && (
                  <>
                    <ToggleOption label="Block Bad Bots" desc="Block Ahrefs, SEMrush and other scrapers" optionKey="blockBadBots" />
                    <ToggleOption label="Prevent Directory Browsing" desc="Hide folder contents from visitors" optionKey="preventDirectoryBrowsing" />
                    <ToggleOption label="Custom Error Pages" desc="Use custom 404, 403, 500 pages" optionKey="customErrorPages" />
                    <ToggleOption label="Prevent Image Hotlinking" desc="Stop other sites from using your images" optionKey="preventHotlinking" />
                    {options.preventHotlinking && (
                      <div style={{ marginTop: '0.5rem' }}>
                        <label style={{ display: 'block', color: '#62646a', fontSize: '0.78rem', marginBottom: '0.3rem' }}>Your domain (e.g. example.com)</label>
                        <input value={options.hotlinkDomain} onChange={e => setOptions({ ...options, hotlinkDomain: e.target.value })} placeholder="example.com" style={{ width: '100%', padding: '8px 12px', border: '1px solid #e4e5e7', borderRadius: '6px', fontSize: '0.82rem', outline: 'none', boxSizing: 'border-box' }} />
                      </div>
                    )}
                    <div style={{ marginTop: '0.75rem' }}>
                      <label style={{ display: 'block', color: '#62646a', fontSize: '0.78rem', fontWeight: 500, marginBottom: '0.3rem' }}>Block IP Addresses (one per line)</label>
                      <textarea value={options.denyIPs} onChange={e => setOptions({ ...options, denyIPs: e.target.value })} placeholder="192.168.1.1&#10;10.0.0.1" rows={3} style={{ width: '100%', padding: '8px 12px', border: '1px solid #e4e5e7', borderRadius: '6px', fontSize: '0.82rem', outline: 'none', resize: 'vertical', boxSizing: 'border-box' }} />
                    </div>
                  </>
                )}

                {activeSection === 'advanced' && (
                  <>
                    <ToggleOption label="Enable CORS" desc="Allow cross-origin requests" optionKey="enableCors" />
                    <div style={{ marginTop: '0.75rem' }}>
                      <label style={{ display: 'block', color: '#62646a', fontSize: '0.78rem', fontWeight: 500, marginBottom: '0.3rem' }}>Custom Redirects (old-path new-url per line)</label>
                      <textarea value={options.customRedirects} onChange={e => setOptions({ ...options, customRedirects: e.target.value })} placeholder="/old-page /new-page&#10;/blog/post-1 /articles/post-1" rows={4} style={{ width: '100%', padding: '8px 12px', border: '1px solid #e4e5e7', borderRadius: '6px', fontSize: '0.82rem', outline: 'none', resize: 'vertical', boxSizing: 'border-box' }} />
                    </div>
                  </>
                )}
              </div>
            </div>

            {/* RIGHT - OUTPUT */}
            <div style={{ background: '#1e1e1e', border: '1px solid #333', borderRadius: '16px', overflow: 'hidden' }}>
              <div style={{ padding: '1rem 1.5rem', borderBottom: '1px solid #333', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div style={{ color: '#d4d4d4', fontWeight: 700, fontSize: '0.88rem' }}>.htaccess</div>
                <div style={{ display: 'flex', gap: '0.5rem' }}>
                  <button onClick={copyCode} style={{ background: copied ? '#1dbf73' : '#2d2d2d', border: '1px solid #444', color: copied ? '#fff' : '#d4d4d4', padding: '5px 12px', borderRadius: '6px', cursor: 'pointer', fontSize: '0.78rem', fontWeight: 600 }}>
                    {copied ? '✓' : '📋'} Copy
                  </button>
                  <button onClick={downloadFile} style={{ background: '#1dbf73', border: 'none', color: '#fff', padding: '5px 12px', borderRadius: '6px', cursor: 'pointer', fontSize: '0.78rem', fontWeight: 600 }}>
                    ⬇️ Download
                  </button>
                </div>
              </div>
              <pre style={{ padding: '1.5rem', color: '#d4d4d4', fontSize: '0.78rem', lineHeight: 1.8, overflow: 'auto', margin: 0, fontFamily: 'Courier New, monospace', minHeight: '500px', whiteSpace: 'pre-wrap' }}>
                {output}
              </pre>
            </div>
          </div>

          {/* FAQ */}
          <div style={{ marginBottom: '2rem' }}>
            <h2 style={{ fontWeight: 700, fontSize: '1.2rem', color: '#404145', marginBottom: '1.25rem' }}>Frequently Asked Questions</h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              {[
                { q: 'What is .htaccess?', a: '.htaccess is a configuration file for Apache web servers. It allows you to control server settings at directory level including redirects, authentication, compression and more.' },
                { q: 'Where do I upload .htaccess?', a: 'Upload .htaccess to the root directory of your website (usually public_html or www folder). It affects that directory and all subdirectories.' },
                { q: 'Will .htaccess slow down my website?', a: '.htaccess is read on every request which adds minimal overhead. However the performance gains from HTTPS redirects, Gzip and browser caching far outweigh this overhead.' },
                { q: 'Can .htaccess break my website?', a: 'Incorrect .htaccess rules can cause errors. Always backup your existing .htaccess before replacing it. Test on staging first if possible.' },
              ].map((faq, i) => (
                <div key={i} style={{ background: '#fff', border: '1px solid #e4e5e7', borderRadius: '8px', padding: '1.25rem' }}>
                  <div style={{ fontWeight: 600, fontSize: '0.92rem', color: '#404145', marginBottom: '0.5rem' }}>{faq.q}</div>
                  <div style={{ color: '#62646a', fontSize: '0.85rem', lineHeight: 1.7 }}>{faq.a}</div>
                </div>
              ))}
            </div>
          </div>

          {/* CREDIT */}
          <div style={{ textAlign: 'center', padding: '1.5rem', background: '#fff', border: '1px solid #e4e5e7', borderRadius: '12px' }}>
            <p style={{ color: '#62646a', fontSize: '0.85rem' }}>
              Built by <strong style={{ color: '#404145' }}>Dev Zeeshan</strong> on{' '}
              <Link href="/" style={{ color: '#1dbf73', textDecoration: 'none', fontWeight: 600 }}>DevLpers</Link>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}